### ISSUE TITLE
Homebrew formulae for JavaScript engines

### ISSUE THREAD

**Issue by mathiasbynens** [mathiasbynens/todo#17]
Being able to install stable versions of major ECMAScript engines through Homebrew would make it much easier to set up [eshost](https://github.com/bterlson/eshost-cli) on macOS, and to just test them out in general. The easier it is to install these engines, the more likely developers are to play around with them and file bugs.

Let’s [create Homebrew formulae](http://docs.brew.sh/Formula-Cookbook.html) for each of them!

- [ ] V8
    - [Formula for v5.1.281.47 (outdated)](https://github.com/Homebrew/homebrew-core/blob/master/Formula/v8.rb)
    - [PR to update formula to v5.8.48](https://github.com/Homebrew/homebrew-core/pull/9343) by @oaleynik
    - [PR for new `v8@5.8` formula](https://github.com/Homebrew/homebrew-core/pull/9392) by @pinepain
    - Recommended: `brew install v8 --with-icu4c --with-readline`
    - [Request to host pre-built binaries for each OS/arch somewhere official](https://bugs.chromium.org/p/v8/issues/detail?id=5918)
- [x] ChakraCore
    - ~~PR: https://github.com/Homebrew/homebrew-core/pull/9323~~
    - Recommended: `brew install chakra --with-icu4c`
    - [Request to host pre-built binaries for each OS/arch somewhere official](https://github.com/Microsoft/ChakraCore/issues/2278#issuecomment-277301120)
    - [Request to add `-v`/`--version` to binary](https://github.com/Microsoft/ChakraCore/issues/2472)
- [ ] SpiderMonkey (`jsshell`)
    - Formula for outdated version: https://github.com/Homebrew/homebrew-core/blob/master/Formula/spidermonkey.rb
    - Should be updated based on `https://archive.mozilla.org/pub/firefox/tinderbox-builds/mozilla-release-macosx64/1486087028/jsshell-mac.zip` where 1486087028 is the build number — PR: https://github.com/Homebrew/homebrew-core/pull/9607
    - [Request to host pre-built binaries for each OS/arch somewhere official](https://bugzilla.mozilla.org/show_bug.cgi?id=1336514)
    - `brew install spidermonkey`
- [ ] JavaScriptCore (`jsc`)
    - [Request to add `-v`/`--version` to `jsc` binary](https://bugs.webkit.org/show_bug.cgi?id=167802)
    - https://trac.webkit.org/wiki/JavaScriptCore
    - not a priority, as a version is available at `/System/Library/Frameworks/JavaScriptCore.framework/Versions/A/Resources/jsc`
- [ ] Nashorn
    - https://wiki.openjdk.java.net/display/Nashorn/Building+Nashorn

Please leave a comment if you want to work on any of these.

**Comment by ariya** [comment]
Is Nashorn necessary in this case? Installing JDK already gives [jrunscript](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/jrunscript.html), a JS shell utilizing Nashorn.

Example: http://esprima.readthedocs.io/en/3.1/getting-started.html#using-esprima-with-rhino-or-nashorn.

**Comment by oaleynik** [comment]
@mathiasbynens thanks for this! Question: currently it installs version 5.1.281.47. Is there any way to install the latest V8?

**Comment by mathiasbynens** [comment]
@oaleynik Someone needs to update the formula for V8. The process is fairly straight-forward — are you up for it? https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md#submit-a-version-upgrade-for-the-foo-formula

**Comment by oaleynik** [comment]
@mathiasbynens I see someone have submitted PR for 5.4: https://github.com/Homebrew/homebrew-core/pull/7168

Also there is a formula for 5.7:
https://github.com/pinepain/homebrew-devtools/blob/master/Formula/v8%405.7.rb

**Comment by oaleynik** [comment]
@mathiasbynens working on PR now. Will update to 5.8.57

**Comment by mathiasbynens** [comment]
@oaleynik Please post a link to the PR here once it’s ready!

**Comment by oaleynik** [comment]
@mathiasbynens will do! I don't have the fast network link here so fetching v8 takes a lot of time :)
I'm actually making formula to build 5.8.48 as default and build latest with `--HEAD` option

**Comment by oaleynik** [comment]
@mathiasbynens https://github.com/Homebrew/homebrew-core/pull/9343

**Comment by oaleynik** [comment]
I'm not sure is it ok to export `d8` executable only though

**Comment by mathiasbynens** [comment]
ChakraCore can now be installed with Homebrew! OP updated.

**Comment by mathiasbynens** [comment]
I’ve started to file requests to host each engine’s pre-built binaries for each OS/arch somewhere official.

* V8: https://bugs.chromium.org/p/v8/issues/detail?id=5918
* ChakraCore: https://github.com/Microsoft/ChakraCore/issues/2278#issuecomment-277301120
* SpiderMonkey: https://bugzilla.mozilla.org/show_bug.cgi?id=1336514

This would simplify the Homebrew formulae and would drastically improve `brew install $engine` performance since we‘d then no longer have to build from source.

**Comment by pinepain** [comment]
Thank you very much! It would be great if they help us, packaging should cost nothing to them after binaries are actually built.

**Comment by mathiasbynens** [comment]
Since [binary formulae aren’t welcome in homebrew-core](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md#we-dont-like-binary-formulae), I’ve created a tap where such formulae can be hosted: https://github.com/mathiasbynens/homebrew-ecmascript

**Comment by mathiasbynens** [comment]
…and [jsvu](https://github.com/GoogleChromeLabs/jsvu) now solves this problem in a much better way. 🎉
